# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# https://github.com/actions

name: Test workflow

on:
  push:
    branches:
      - 'master'
    paths:
      - 'src/**'
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup dotnet 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Diagnostic print enviroment vars
      run: printenv

    - name: testcon
      run: curl -o google_de_homepage.html http://www.google.de
    
    - name: pwsh ver
      run: pwsh --version

    - name: java ver
      run: javac --version

    - name: Install dotnet toolkit -> Coree.DotnetTool.ToolKit 
      run: dotnet tool install -g Coree.DotnetTool.ToolKit

    - name: echo
      run: echo "$PWD"
